// <auto-generated />
namespace Movie_Ticket_Booking_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initialdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialdata));
        
        string IMigrationMetadata.Id
        {
            get { return "202212070846034_Initialdata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
