// <auto-generated />
namespace Movie_Ticket_Booking_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class frontendoffice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(frontendoffice));
        
        string IMigrationMetadata.Id
        {
            get { return "202212171132205_frontendoffice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
